version: '3.3'
services:
  app:
    image: victorgso001/alpine-php-mongo:latest
    container_name: dojoapp_api
    volumes:
      - ./:/home/project-folder
    links:
      - mongo
    networks:
      - app-network

  webserver:
    image: victorgso001/nginx-server
    container_name: webserver
    tty: true
    ports:
      - "8002:80"
    volumes:
      - ./:/home/project-folder
    networks:
      - app-network
      - default

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dojo_jkc
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: dojo_jkc_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    links:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dojo_jkc_admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - /server:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
