version: '3.3'
services:
  app:
    image: lissonpsantos2/ubuntu-phps:latest
    container_name: dojo_supervisor_api
    volumes:
      - ./:/home/project-folder
    command: bash -c "selectphp 7.2 && apachelinker /home/project-folder/public && tail -f /tmp/dev.log"
    ports:
      - 8010:80
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: dojo_jkc
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: dojo_jkc_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dojo_jkc_admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    volumes:
      - /server:/data/db
    networks:
      - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
